// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDhoBUcstgG5IhqTbv590eNT1rA1iSAto',
    appId: '1:751792416501:web:0234145c2170d08bfc87bc',
    messagingSenderId: '751792416501',
    projectId: 'flutter-trivia-quiz',
    authDomain: 'flutter-trivia-quiz.firebaseapp.com',
    storageBucket: 'flutter-trivia-quiz.appspot.com',
    measurementId: 'G-9BBDHR438C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8K3y_HwqPkAVI4BpdhJK8V7rofKLuNnA',
    appId: '1:751792416501:android:8eb3052718a0a3d0fc87bc',
    messagingSenderId: '751792416501',
    projectId: 'flutter-trivia-quiz',
    storageBucket: 'flutter-trivia-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjTPyWQflPnFEWfaH3xXOiK26a3F2lyBc',
    appId: '1:751792416501:ios:0187ab4603514fa9fc87bc',
    messagingSenderId: '751792416501',
    projectId: 'flutter-trivia-quiz',
    storageBucket: 'flutter-trivia-quiz.appspot.com',
    iosBundleId: 'com.example.trivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjTPyWQflPnFEWfaH3xXOiK26a3F2lyBc',
    appId: '1:751792416501:ios:0187ab4603514fa9fc87bc',
    messagingSenderId: '751792416501',
    projectId: 'flutter-trivia-quiz',
    storageBucket: 'flutter-trivia-quiz.appspot.com',
    iosBundleId: 'com.example.trivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDhoBUcstgG5IhqTbv590eNT1rA1iSAto',
    appId: '1:751792416501:web:2bf63a314ca077e6fc87bc',
    messagingSenderId: '751792416501',
    projectId: 'flutter-trivia-quiz',
    authDomain: 'flutter-trivia-quiz.firebaseapp.com',
    storageBucket: 'flutter-trivia-quiz.appspot.com',
    measurementId: 'G-XCYJHS1W1M',
  );
}
